"""Python là ngôn ngữ thông dịch (interpreted language), không phải ngôn ngữ biên dịch (compiled language). Vì
- Interpreted: khi chạy mã python, trình thông dịch sẽ đọc mã nguồn và thực thi từng dòng lệnh ngay lập tức. trình thông dịch chuyển mã nguồn thành mã máy từng dòng một khi thực thi,
không cần tạo ra một tệp nhị phân độc lập trước khi chạy chương trình
- Không cần quá nhiều trình biên dịch trước Không giống như ngôn ngữ biên dịch C or C++, nơi mã nguồn phải được biên dịch thành mã máy trước khi có thể chạy chương trình, mã python
có thể chạy trực tiếp mà không cần bước biện dịch trước
-Tính linh hoạt và dễ dàng sử dụng vì python là một ngôn ngữ thông dịch , nó mang lại tính linh hoạt cao và giúp phát triển nhanh chóng. Lập trình viên có thể viết và kiểm tra ngay 
lập tức, điều này rất hữu ích cho việc phát triển nhanh chóng. Lập trình viên có thể viết và kiểm tra ngay lập tức, điều này rất hữu ích cho việc phất triển va gỡ lỗi
- Protable: mã python có thể chạy trên nhiều nền tảng khác nhau mà không cần phải biên dịch lại cho từng nền tảng cụ thể""" 
print("contest")